version: 2

sources:
  - name: raw
    schema : gz_raw_data
    description: greenweez raw data source
    tables:
      - name: product
        identifier : raw_gz_product
        description: products of greeweez
        columns:
          - name: products_id
            description: Primary Key of the table
            tests:
              - unique
              - not_null
      - name: sales
        identifier : raw_gz_sales
        description: sales of greenweez / we have one row per product_id found in each order_id.
        columns:
          - name: date_date
            description: the date of the purchase
        tests:
          - unique:
              column_name: "(orders_id || '-' || pdt_id)"
      - name: ship
        identifier : raw_gz_ship
        description: ship of greeweez
        columns:
          - name: orders_id
            description: Primary Key of the table
            tests:
              - unique
              - not_null